# Generated by Django 6.0.2 on 2026-03-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_order_delivery_status_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='category/'),
        ),
    ]
