# Generated by Django 6.0.2 on 2026-03-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_order_delivery_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100, unique=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
