# Generated by Django 4.2 on 2026-03-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0014_orderitem_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
