# Generated by Django 4.2 on 2026-03-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0015_alter_orderitem_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='VAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='category/'),
        ),
    ]
