# Generated by Django 4.2 on 2026-03-22 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0017_deliveryagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demoapp.deliveryagent'),
        ),
    ]
