# Generated by Django 4.2 on 2026-03-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0018_order_delivery_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_restored',
            field=models.BooleanField(default=False),
        ),
    ]
